name: Continuous Deployment

on:
  workflow_dispatch: #workflow_dispatch allows you to manually trigger the workflow from the Github actions tab. 
  #workflow_run: it runs when the workflow run is completed automatically.
    workflows:
      - Continuous Integration
    types:
      - completed

jobs:
  deploy:

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest
    steps:

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        env:
          IMAGE_TAG: ${{ github.event.workflow_run.head_sha }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: IMAGE_TAG
          script: |
            echo "======================================"
            echo "Deploying AI Trading API"
            echo "Commit SHA : ${IMAGE_TAG}"
            echo "======================================"
            
            docker pull rajnishk2439/ai-trading-api:${IMAGE_TAG}
            docker pull rajnishk2439/ai-trading-api:latest

            docker stop trading-api || true

            docker rm trading-api || true

            docker run -d \
              --name trading-api \
              --restart unless-stopped \
              -p 8000:8000 \
              --env-file /home/ubuntu/ai-trading-research-agent/.env \
              -e APP_VERSION=${IMAGE_TAG} \
              rajnishk2439/ai-trading-api:${IMAGE_TAG}

            echo "Waiting for application to become healthy..."

            for i in {1..30}; do

              if curl --fail http://localhost:8000/health; then
                echo "Application is healthy."
                exit 0
              fi

              echo "Waiting... ($i/30)"
              sleep 5

            done

            echo "Health check failed after waiting."

            docker logs trading-api

            exit 1